# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'recipesbook' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for recipesbook
  pod 'RxSwift','~>5.0'
  pod 'RxCocoa','~>5.0'

  target 'recipesbookTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'recipesbookUITests' do
    # Pods for testing
  end

end
